---
- name: "Atualizando repositórios"
  apt:
    update_cache: yes

- name: "Instalando pacotes"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - "{{ packages }}"

- name: "Habilitando repo do flathub"
  shell:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          
